class AppString {
  static String appTitle = 'Hızlı Flutter';
  static String ok = 'Tamam';
  static String widget = 'Widget';
  static String news = 'Haber';
  static String answer = 'Soru';
  static String examples = 'Örnekler';
  static String timeIsUp = 'Zaman Doldu';
  static String newQuestionComing = 'Yeni soru geliyor...';
  static String wrong = 'Yanlış';
  static String correct = 'Doğru';
  static String sorryWrongAnswer = 'Maalesef yanlış cevap!';
  static String congratsOnTheCorrectAnswer = 'Tebrikler doğru cevap!';
  static String questionsDone = 'Sorular Bitti';
  static String numberOfCorrect = 'Doğru Sayısı';
  static String numberOfInCorrect = 'Yanlış Sayısı';
  static String totalPoints = 'Toplam Puan';
  static String source = 'Kaynak';
  static String imageRemoved = 'Kaynak';
  static String recent = 'Yeni';
  static String dayAgo = 'Gün Önce';
  static String yearAgo = 'Yıl Önce';
  static String easy = 'Basit';
  static String middle = 'Orta';
  static String hard = 'Zor';
  static String preview = 'Ön izleme';
  static String code = 'Kod';
  static String featureSearch = 'Özellik Ara...';
  static String features = 'Özellikler';
  static String codeLinkCopied = 'Kod linki kopyalandı!';
  static String codeCopied = 'Kod kopyalandı!';
  static String showInBrowser = 'Tarayıcıda Göster';
  static String zoomOut = 'Uzaklaştır';
  static String zoomIn = 'Yakınlaştır';

  static String sslWebUrl = 'https://webservice.yazilimmotoru.com/';
  static String webUrl = 'http://webservice.yazilimmotoru.com/';
  static String webDataUrl = 'api.php/records/';
}
